{
 "title": "Netatmo Weather Station",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "station",
    "label": "Station",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"netatmo\",\r\n  tag: \"station\",\r\n  predicate: (r) => true\r\n)\r\n"
   },
   {
    "name": "temp_module",
    "label": "Temperature Module",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"netatmo\",\r\n  tag: \"module\",\r\n  predicate: (r) => (r.station == \"${station}\" and (r.type == \"NAModule4\" or r.type == \"NAMain\"))\r\n)\r\n"
   },
   {
    "name": "rain_module",
    "label": "Rain Module",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"netatmo\",\r\n  tag: \"module\",\r\n  predicate: (r) => (r.station == \"${station}\" and r.type == \"NAModule3\")\r\n)\r\n"
   },
   {
    "name": "wind_module",
    "label": "Wind Module",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"netatmo\",\r\n  tag: \"module\",\r\n  predicate: (r) => (r.station == \"${station}\" and r.type == \"NAModule2\")\r\n)\r\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Station",
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"height:100%;display:flex;justify-content:center;align-items:center;\">\n<h1 style=\"font-size:300%;font-weight:bold;\">$station</h1>\n</div>"
   }
  },
  {
   "title": "Timezone",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "timezone",
     "query": "from(bucket: \"netatmo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"station\"] == \"${station}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"timezone\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> keep(columns: [\"_value\", \"module\"])\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "Noise",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "alias": "$tag_station $tag_module",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "noise",
     "query": "from(bucket: \"netatmo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"station\"] == \"${station}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"noise\")\r\n  |> sort(columns: [\"_time\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> keep(columns: [\"_value\", \"_time\", \"module\"])\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "Noise Level",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_station $tag_module",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "noise",
     "query": "from(bucket: \"netatmo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"station\"] == \"${station}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"noise\")\r\n  |> sort(columns: [\"_time\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$Module$/" }
     ]
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altitude",
     "query": "from(bucket: \"netatmo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"station\"] == \"${station}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"altitude\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "alias": "$tag_station $tag_module",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "co2",
     "query": "from(bucket: \"netatmo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"co2\")\r\n  |> filter(fn: (r) => r[\"module\"] =~ /${temp_module:pipe}/)\r\n  |> sort(columns: [\"_time\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_value\", \"_time\", \"module\"])\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperatur",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$tag_station $tag_module",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "co2",
     "query": "from(bucket: \"netatmo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"module\"] =~ /${temp_module:pipe}/)\r\n  |> sort(columns: [\"_time\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_value\", \"_time\", \"module\"])\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "targets": [
    {
     "alias": "$tag_station $tag_module",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pressure",
     "query": "from(bucket: \"netatmo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pressure\")\r\n  |> filter(fn: (r) => r[\"station\"] == \"${station}\")\r\n  |> sort(columns: [\"_time\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_value\", \"_time\", \"module\"])\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "Pressure Trend",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pressure_trend",
     "query": "from(bucket: \"netatmo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pressure_trend\")\r\n  |> filter(fn: (r) => r[\"station\"] == \"${station}\")\r\n  |> sort(columns: [\"_time\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> keep(columns: [\"_value\", \"_time\"])\r\n  |> rename(columns: {_value: \"Trend\"})\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  { "title": "$temp_module", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }, "repeat": "temp_module" },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$tag_station $tag_module",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "query": "from(bucket: \"netatmo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"module\"] == \"${temp_module}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\r\n  |> sort(columns: [\"_time\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> keep(columns: [\"_value\", \"_time\", \"module\"])\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=~", "value": "/^$Module$/" },
      { "condition": "AND", "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "Current",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "query": "  from(bucket: \"netatmo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"module\"] == \"${temp_module}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\r\n  |> sort(columns: [\"_time\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=~", "value": "/^$Module$/" },
      { "condition": "AND", "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "Max",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "max_temp",
     "query": "from(bucket: \"netatmo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"module\"] == \"${temp_module}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"max_temp\")\r\n  |> sort(columns: [\"_time\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=~", "value": "/^$Module$/" },
      { "condition": "AND", "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_station $tag_module",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "humidity",
     "query": "from(bucket: \"netatmo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"module\"] == \"${temp_module}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"humidity\")\r\n  |> sort(columns: [\"_time\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=~", "value": "/^$Module$/" },
      { "condition": "AND", "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "Signal",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rf_status",
     "query": "from(bucket: \"netatmo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"module\"] == \"${temp_module}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rf_status\")\r\n  |> sort(columns: [\"_time\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({r with _value: (float(v: r._value) * -1.0)} ))\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$Module$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery_percent",
     "query": "from(bucket: \"netatmo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"module\"] == \"${temp_module}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"battery_percent\")\r\n  |> sort(columns: [\"_time\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=~", "value": "/^$Module$/" },
      { "condition": "AND", "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature Trend",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "temp_trend",
     "query": "from(bucket: \"netatmo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"module\"] == \"${temp_module}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temp_trend\")\r\n  |> sort(columns: [\"_time\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> keep(columns: [\"_value\", \"_time\"])\r\n  |> rename(columns: {_value: \"Trend\"})\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$Module$/" }
     ]
    }
   ]
  },
  {
   "title": "Min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "min_temp",
     "query": "from(bucket: \"netatmo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"module\"] == \"${temp_module}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"min_temp\")\r\n  |> sort(columns: [\"_time\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=~", "value": "/^$Module$/" },
      { "condition": "AND", "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  { "title": "$rain_module", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 }, "repeat": "rain_module" },
  {
   "title": "Rain",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "suffix: mm" } },
   "targets": [
    {
     "alias": "$tag_station $tag_module",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "query": "from(bucket: \"netatmo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"module\"] == \"${rain_module}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rain\")\r\n  |> sort(columns: [\"_time\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_value\", \"_time\", \"module\"])\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=~", "value": "/^$Module$/" },
      { "condition": "AND", "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "Summary (Last Hour)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "suffix: mm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "query": "from(bucket: \"netatmo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"module\"] == \"${rain_module}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sum_rain_1\")\r\n  |> sort(columns: [\"_time\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=~", "value": "/^$Module$/" },
      { "condition": "AND", "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "Summary (Today)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "suffix: mm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "query": "from(bucket: \"netatmo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"module\"] == \"${rain_module}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sum_rain_24\")\r\n  |> sort(columns: [\"_time\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=~", "value": "/^$Module$/" },
      { "condition": "AND", "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "Signal",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 20, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rf_status",
     "query": "from(bucket: \"netatmo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"module\"] == \"${rain_module}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rf_status\")\r\n  |> sort(columns: [\"_time\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({r with _value: (float(v: r._value) * -1.0)} ))\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$Module$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery_percent",
     "query": "from(bucket: \"netatmo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"module\"] == \"${rain_module}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"battery_percent\")\r\n  |> sort(columns: [\"_time\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=~", "value": "/^$Module$/" },
      { "condition": "AND", "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  { "title": "$wind_module", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 }, "repeat": "wind_module" },
  {
   "title": "Wind",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "alias": "$tag_station $tag_module",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "query": "from(bucket: \"netatmo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"module\"] == \"${wind_module}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"windstrength\")\r\n  |> sort(columns: [\"_time\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> keep(columns: [\"_value\", \"_time\", \"module\"])\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=~", "value": "/^$Module$/" },
      { "condition": "AND", "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "Gust",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "alias": "$tag_station $tag_module",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "query": "from(bucket: \"netatmo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"module\"] == \"${wind_module}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"guststrength\")\r\n  |> sort(columns: [\"_time\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> keep(columns: [\"_value\", \"_time\", \"module\"])\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=~", "value": "/^$Module$/" },
      { "condition": "AND", "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "Wind Angle",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pressure_trend",
     "query": "from(bucket: \"netatmo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"module\"] == \"${wind_module}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"windangle\")\r\n  |> sort(columns: [\"_time\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> keep(columns: [\"_value\", \"_time\"])\r\n  |> rename(columns: {_value: \"Angle\"})\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "Gust Angle",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pressure_trend",
     "query": "from(bucket: \"netatmo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"module\"] == \"${wind_module}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gustangle\")\r\n  |> sort(columns: [\"_time\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> keep(columns: [\"_value\", \"_time\"])\r\n  |> rename(columns: {_value: \"Angle\"})\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  {
   "title": "Signal",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 20, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rf_status",
     "query": "from(bucket: \"netatmo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"module\"] == \"${wind_module}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rf_status\")\r\n  |> sort(columns: [\"_time\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({r with _value: (float(v: r._value) * -1.0)} ))\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$Module$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery_percent",
     "query": "from(bucket: \"netatmo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"module\"] == \"${wind_module}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"battery_percent\")\r\n  |> sort(columns: [\"_time\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=~", "value": "/^$Module$/" },
      { "condition": "AND", "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  }
 ]
}