name: Build Docker Image

on:
  - push

jobs:
  build_image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: login to docker hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: create builder
      run: |
        docker buildx create --name multi-arch-builder --use
    - name: debug builder
      run: |
        docker buildx inspect --bootstrap
    - name: build image
      run: |
        docker buildx build --push \
        --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 \
        --tag $GITHUB_REPOSITORY:$GITHUB_REF .
